# Generated by Django 4.0.3 on 2022-04-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrationdetails',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='studentregistrationdetails',
            name='phoneno',
        ),
    ]
