# Generated by Django 4.0.3 on 2022-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0002_remove_studentregistrationdetails_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpadcollectiondetails',
            name='pads_collected',
            field=models.CharField(default=1, max_length=30, verbose_name='Number of Pads Collected'),
            preserve_default=False,
        ),
    ]
