# Generated by Django 4.0.3 on 2022-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0003_studentpadcollectiondetails_pads_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinstudentpadtable',
            name='pads_collected',
            field=models.CharField(default=1, max_length=30, verbose_name='Number of Pads Collected'),
            preserve_default=False,
        ),
    ]
