# Generated by Django 4.0.3 on 2022-06-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0005_user_remove_studentregistrationdetails_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpadcollectiondetails',
            name='regno',
        ),
    ]
