# Generated by Django 4.0.3 on 2022-11-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0010_alter_subcounty_options_subcounty_regno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCounty',
        ),
    ]
