# Generated by Django 4.0.3 on 2022-11-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0011_delete_subcounty'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty_name', models.CharField(max_length=255)),
                ('regno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_county', to='fulalapp.studentregistrationdetails', verbose_name='student ID')),
            ],
            options={
                'verbose_name_plural': 'sub county',
            },
        ),
    ]
