# Generated by Django 4.0.3 on 2022-11-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0012_subcounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='regno',
        ),
    ]
