# Generated by Django 4.0.3 on 2022-11-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0013_remove_subcounty_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpadcollectiondetails',
            name='regno',
        ),
    ]
