# Generated by Django 4.0.3 on 2022-11-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0014_remove_studentpadcollectiondetails_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpadcollectiondetails',
            name='regno',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='pad_collection', to='fulalapp.studentregistrationdetails', verbose_name='Student ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcounty',
            name='regno',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sub_county', to='fulalapp.studentregistrationdetails', verbose_name='student ID'),
            preserve_default=False,
        ),
    ]
