# Generated by Django 4.0.3 on 2022-11-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0016_studentregistrationdetails_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='regno',
        ),
    ]
