# Generated by Django 4.0.3 on 2022-11-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0017_remove_subcounty_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='regno',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, related_name='sub_county', to='fulalapp.studentregistrationdetails', verbose_name='student ID'),
            preserve_default=False,
        ),
    ]
