# Generated by Django 4.0.3 on 2022-11-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0020_subcounty_regno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrationdetails',
            name='regno',
        ),
    ]
