# Generated by Django 4.0.3 on 2022-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0021_remove_studentregistrationdetails_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationdetails',
            name='regno',
            field=models.CharField(default=6666666, max_length=50, verbose_name='Student Registrartion Number'),
            preserve_default=False,
        ),
    ]
