# Generated by Django 4.1.4 on 2022-12-11 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0023_remove_subcounty_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpadcollectiondetails',
            name='collection_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Collection Date'),
        ),
    ]
