# Generated by Django 4.1.4 on 2022-12-11 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0024_alter_studentpadcollectiondetails_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpadcollectiondetails',
            name='collection_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Collection Date'),
        ),
    ]
