# Generated by Django 4.1.5 on 2023-02-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulalapp', '0025_alter_studentpadcollectiondetails_collection_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
